// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------- //
// probe_swd //
// --------- //

#define probe_swd_wrap_target 0
#define probe_swd_wrap 13
#define probe_swd_pio_version 0

#define probe_swd_offset_start 0u
#define probe_swd_offset_write_bits 2u
#define probe_swd_offset_read_bits 8u

static const uint16_t probe_swd_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block
    0x60a8, //  1: out    pc, 8
    0x6025, //  2: out    x, 5
    0xe081, //  3: set    pindirs, 1
    0x7201, //  4: out    pins, 1         side 0 [2]
    0x1a44, //  5: jmp    x--, 4          side 1 [2]
    0xf001, //  6: set    pins, 1         side 0
    0x0000, //  7: jmp    0
    0x6025, //  8: out    x, 5
    0xf080, //  9: set    pindirs, 0      side 0
    0x5a01, // 10: in     pins, 1         side 1 [2]
    0x124a, // 11: jmp    x--, 10         side 0 [2]
    0x8020, // 12: push   block
    0x0000, // 13: jmp    0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program probe_swd_program = {
    .instructions = probe_swd_program_instructions,
    .length = 14,
    .origin = -1,
    .pio_version = probe_swd_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config probe_swd_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + probe_swd_wrap_target, offset + probe_swd_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

