"""
Minimal Thumb-2 flash-read algorithm — loaded into target RAM and
executed on the target CPU to bulk-read flash without the debug-bus
AHB-AP touching the actual data path.

See `cortex_m_read.S` for the source.

Why this exists:
  nRF5340 (and similar anti-tamper MCUs) throttle the AHB-AP after a
  small number of debug-bus reads. J-Link sidesteps this by running a
  small Thumb program on the target CPU — the CPU's own AHB master
  reads flash through the same channel firmware uses, which the chip
  does NOT monitor for anti-tamper. Only the final RAM-buffer read goes
  through AHB-AP. A 1 MB dump costs ~1 K AP reads instead of ~16 K.

Calling convention (set via DCRSR/DCRDR before invocation):
  R0 = source flash address     (word-aligned)
  R1 = word count                (0..N)
  R2 = destination RAM buffer    (word-aligned)
  PC = ALGO_ADDR (algo loaded base)
  MSP = stack top (any valid RAM ptr; we don't use stack)
  XPSR = 0x01000000  (T bit set)

When count words have been copied, the algo executes BKPT #0, which
halts the CPU. The driver polls DHCSR.S_HALT, then reads the buffer
from RAM via a single AHB-AP block read.

Rebuild after editing cortex_m_read.S:
  cd flash_algos && ./build.sh
Then update ALGO_THUMB below from the script's "python literal" output.
"""

# 16 bytes, generated by ./build.sh from cortex_m_read.S
# Disassembly:
#   0: b129          cbz r1, done
#   2: f850 3b04     ldr.w r3, [r0], #4
#   6: f842 3b04     str.w r3, [r2], #4
#   a: 3901          subs r1, #1
#   c: d1f9          bne.n read_loop
#   e: be00          bkpt #0
ALGO_THUMB = bytes([
    0x29, 0xb1, 0x50, 0xf8, 0x04, 0x3b, 0x42, 0xf8,
    0x04, 0x3b, 0x01, 0x39, 0xf9, 0xd1, 0x00, 0xbe,
])
assert len(ALGO_THUMB) == 16

# Default RAM layout for nRF5340 (App core has 512 KB SRAM @ 0x20000000).
# We pick addresses deep enough into RAM that they don't collide with
# TF-M secure RAM (typically lower 64 KB) or MPU-protected boot regions.
# 0x20030000 + 16 KB algo+buffer area = well within free RAM.
DEFAULT_ALGO_ADDR   = 0x20030000   # 16 bytes for the algo itself
DEFAULT_BUFFER_ADDR = 0x20030400   # 4 KB max buffer (1024 words)
DEFAULT_STACK_TOP   = 0x20031400   # ~4 KB stack headroom (we don't push anything)
DEFAULT_BUFFER_WORDS_MAX = 1024    # 4 KB per algo run (tunable)

# nRF5340 Net core has 64 KB SRAM @ 0x21000000. Same scheme, lower base.
NET_CORE_ALGO_ADDR   = 0x21000000
NET_CORE_BUFFER_ADDR = 0x21000400
NET_CORE_STACK_TOP   = 0x21001400
NET_CORE_BUFFER_WORDS_MAX = 512    # 2 KB per algo run for the smaller-RAM Net core
